Global:
  use_gpu: True
  epoch_num: 30
  log_smooth_window: 20
  print_batch_step: 1
  save_model_dir: /home/aistudio/output/rec_red26_train
  save_epoch_step: 30
  # evaluation is run every 0 iterations after the 1250th iteration
  eval_batch_step: [0, 40000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir: /home/aistudio/output/rec_red26_train
  use_visualdl: False
  infer_img: 
  # for data or label process
  character_dict_path: /home/aistudio/work/label_dict.txt
  character_type: ch
  max_text_length: 83
  infer_mode: False
  use_space_char: False


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: RedNet
    layers: 26
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 128
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data
    label_file_list: ["/home/aistudio/data/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 8
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/data
    label_file_list: ["/home/aistudio/data/rec/rec_gt_eval.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 8
    use_shared_memory: False
